export const APP_ERROR_CODES = {
  INVALID_LOGIN_CREDENTIALS: 'INVALID_LOGIN_CREDENTIALS',
  MISSING_AUTH_TOKEN: 'MISSING_AUTH_TOKEN',
  INVALID_AUTH_TOKEN_PAYLOAD: 'INVALID_AUTH_TOKEN_PAYLOAD',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  ACCOUNT_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export type AppErrorCode = (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
